// database.ts
const database = {
    "en": {
        "vocabulary": [
            // Difficulty 1 (4 questions)
            { "id": "en-vocab-1-1", "difficulty": 1, "type": "mcq" as const, "question": "Choose the synonym of 'big'", "options": ["small", "large", "tiny", "short"], "answer": "large" },
            { "id": "en-vocab-1-2", "difficulty": 1, "type": "mcq" as const, "question": "What is the meaning of 'cold'?", "options": ["hot temperature", "low temperature", "warm temperature", "normal temperature"], "answer": "low temperature" },
            { "id": "en-vocab-1-3", "difficulty": 1, "type": "mcq" as const, "question": "Select the opposite of 'up'", "options": ["down", "high", "top", "over"], "answer": "down" },
            { "id": "en-vocab-1-4", "difficulty": 1, "type": "mcq" as const, "question": "Which word means 'to ask a question'?", "options": ["answer", "reply", "question", "tell"], "answer": "question" },
            // Difficulty 2 (4 questions)
            { "id": "en-vocab-2-1", "difficulty": 2, "type": "mcq" as const, "question": "Choose the synonym for 'quick'", "options": ["slow", "fast", "rapid", "lethargic"], "answer": "fast" },
            { "id": "en-vocab-2-2", "difficulty": 2, "type": "mcq" as const, "question": "What does 'beautiful' mean?", "options": ["ugly", "pretty", "plain", "homely"], "answer": "pretty" },
            { "id": "en-vocab-2-3", "difficulty": 2, "type": "mcq" as const, "question": "Select the antonym of 'easy'", "options": ["simple", "hard", "effortless", "light"], "answer": "hard" },
            { "id": "en-vocab-2-4", "difficulty": 2, "type": "mcq" as const, "question": "Which word describes something that happens every day?", "options": ["weekly", "monthly", "daily", "yearly"], "answer": "daily" },
            // Difficulty 3 (4 questions)
            { "id": "en-vocab-3-1", "difficulty": 3, "type": "mcq" as const, "question": "Choose the synonym of 'intelligent'", "options": ["stupid", "clever", "foolish", "dumb"], "answer": "clever" },
            { "id": "en-vocab-3-2", "difficulty": 3, "type": "mcq" as const, "question": "What does 'essential' mean?", "options": ["unnecessary", "important", "optional", "extra"], "answer": "important" },
            { "id": "en-vocab-3-3", "difficulty": 3, "type": "mcq" as const, "question": "Select the antonym of 'generous'", "options": ["kind", "selfish", "charitable", "benevolent"], "answer": "selfish" },
            { "id": "en-vocab-3-4", "difficulty": 3, "type": "mcq" as const, "question": "Which word describes a feeling of great happiness?", "options": ["sadness", "joy", "anger", "fear"], "answer": "joy" },
            // Difficulty 4 (4 questions)
            { "id": "en-vocab-4-1", "difficulty": 4, "type": "mcq" as const, "question": "Choose the synonym for 'significant'", "options": ["minor", "important", "trivial", "negligible"], "answer": "important" },
            { "id": "en-vocab-4-2", "difficulty": 4, "type": "mcq" as const, "question": "What does 'meticulous' mean?", "options": ["careless", "detailed", "sloppy", "hasty"], "answer": "detailed" },
            { "id": "en-vocab-4-3", "difficulty": 4, "type": "mcq" as const, "question": "Select the antonym of 'optimistic'", "options": ["hopeful", "pessimistic", "positive", "upbeat"], "answer": "pessimistic" },
            { "id": "en-vocab-4-4", "difficulty": 4, "type": "mcq" as const, "question": "Which word means 'to make something better'?", "options": ["worsen", "damage", "improve", "reduce"], "answer": "improve" },
            // Difficulty 5 (4 questions) - False Cognates (Portuguese Speaker Focus) + True/False
            { "id": "en-vocab-5-1", "difficulty": 5, "type": "mcq" as const, "question": "Choose the best translation for 'actually' in 'Actually, I am tired.'", "options": ["atualmente", "na verdade", "pretender", "fabricar"], "answer": "na verdade" },
            { "id": "en-vocab-5-2", "difficulty": 5, "type": "mcq" as const, "question": "Which option correctly uses 'intend'?", "options": ["I pretend to go to the party.", "I intend to go to the party.", "I fabric to go to the party.", "I realize to go to the party."], "answer": "I intend to go to the party." },
            { "id": "en-vocab-5-3", "difficulty": 5, "type": "true_false", "statement": "Statement: 'Fabric' in English means 'fábrica' in Portuguese.", "correctAnswer": false },
            { "id": "en-vocab-5-4", "difficulty": 5, "type": "true_false", "statement": "Statement: 'Realize' in English usually translates to 'realizar' in Portuguese.", "correctAnswer": false },
            // Difficulty 6 (4 questions) - Hard False Cognates + True/False
            { "id": "en-vocab-6-1", "difficulty": 6, "type": "mcq" as const, "question": "Select the best Portuguese translation for 'successful' in 'He was a successful businessman.'", "options": ["sucessoso", "exitoso", "afortunado", "consecutivos"], "answer": "exitoso" },
            { "id": "en-vocab-6-2", "difficulty": 6, "type": "mcq" as const, "question": "Which sentence correctly uses the English word 'sensible' (in the meaning of 'reasonable')?", "options": ["He is a sensible person, he feels everything.", "He made a sensible decision to stay home in the storm.", "The dress is very sensible, you can touch it.", "She is sensible to sunlight."], "answer": "He made a sensible decision to stay home in the storm." },
            { "id": "en-vocab-6-3", "difficulty": 6, "type": "true_false", "statement": "Statement: 'Costume' in English, when referring to clothing, means 'costume' in Portuguese.", "correctAnswer": false },
            { "id": "en-vocab-6-4", "difficulty": 6, "type": "true_false", "statement": "Statement: 'Parents' in English translates to 'parentes' in Portuguese.", "correctAnswer": false }
        ],
        "reading": [
            // Difficulty 1 (4 questions)
            { "id": "en-read-1-1", "difficulty": 1, "type": "mcq" as const, "text": "The cat sat on the mat.", "question": "Where did the cat sit?", "options": ["On the chair", "On the floor", "On the mat", "On the table"], "answer": "On the mat" },
            { "id": "en-read-1-2", "difficulty": 1, "type": "mcq" as const, "text": "Birds fly in the sky.", "question": "Where do birds fly?", "options": ["In the sea", "On the ground", "In the sky", "In the trees"], "answer": "In the sky" },
            { "id": "en-read-1-3", "difficulty": 1, "type": "mcq" as const, "text": "We drink water when we are thirsty.", "question": "Why do we drink water?", "options": ["When we are hungry", "When we are sleepy", "When we are thirsty", "When we are cold"], "answer": "When we are thirsty" },
            { "id": "en-read-1-4", "difficulty": 1, "type": "mcq" as const, "text": "The book is on the table.", "question": "Where is the book?", "options": ["Under the chair", "On the table", "In the bag", "Next to the bed"], "answer": "On the table" },
            // Difficulty 2 (4 questions)
            { "id": "en-read-2-1", "difficulty": 2, "type": "mcq" as const, "text": "She has a red car. The car is very fast.", "question": "What color is her car?", "options": ["Blue", "Red", "Green", "Yellow"], "answer": "Red" },
            { "id": "en-read-2-2", "difficulty": 2, "type": "mcq" as const, "text": "He plays football in the park every Sunday. He enjoys it very much.", "question": "When does he play football?", "options": ["Every Monday", "Every Saturday", "Every Sunday", "Every Friday"], "answer": "Every Sunday" },
            { "id": "en-read-2-3", "difficulty": 2, "type": "mcq" as const, "text": "They live in a small house. It has two bedrooms and a garden.", "question": "How many bedrooms does their house have?", "options": ["One", "Two", "Three", "Four"], "answer": "Two" },
            { "id": "en-read-2-4", "difficulty": 2, "type": "mcq" as const, "text": "The weather today is sunny and warm. Many people are at the beach.", "question": "How is the weather today?", "options": ["Cloudy and cold", "Rainy and windy", "Sunny and warm", "Stormy and wet"], "answer": "Sunny and warm" },
            // Difficulty 3 (4 questions)
            { "id": "en-read-3-1", "difficulty": 3, "type": "mcq" as const, "text": "Although it was raining, they went for a walk. They took umbrellas with them.", "question": "Why did they take umbrellas?", "options": ["Because it was sunny", "Because it was snowing", "Because it was raining", "Because it was windy"], "answer": "Because it was raining" },
            { "id": "en-read-3-2", "difficulty": 3, "type": "mcq" as const, "text": "The teacher asked the students to read chapter three for homework. They should be ready to discuss it in class tomorrow.", "question": "What should the students read for homework?", "options": ["Chapter one", "Chapter two", "Chapter three", "Chapter four"], "answer": "Chapter three" },
            { "id": "en-read-3-3", "difficulty": 3, "type": "mcq" as const, "text": "She wanted to bake a cake, but she didn't have any eggs. So, she went to the store to buy some.", "question": "Why did she go to the store?", "options": ["To buy milk", "To buy flour", "To buy eggs", "To buy sugar"], "answer": "To buy eggs" },
            { "id": "en-read-3-4", "difficulty": 3, "type": "mcq" as const, "text": "After finishing work, he decided to relax by watching a movie. He made popcorn and sat on the sofa.", "question": "What did he decide to do after work?", "options": ["Go for a run", "Read a book", "Watch a movie", "Cook dinner"], "answer": "Watch a movie" },
            // Difficulty 4 (4 questions)
            { "id": "en-read-4-1", "difficulty": 4, "type": "mcq" as const, "text": "Despite feeling tired, she completed her project. She stayed up late to ensure everything was perfect.", "question": "Why did she stay up late?", "options": ["Because she was bored", "To watch TV", "To complete her project", "To clean the house"], "answer": "To complete her project" },
            { "id": "en-read-4-2", "difficulty": 4, "type": "mcq" as const, "text": "The old house stood on a hill overlooking the town. It had been empty for many years and was surrounded by tall trees.", "question": "Where was the old house located?", "options": ["In the town center", "By the river", "On a hill", "In the valley"], "answer": "On a hill" },
            { "id": "en-read-4-3", "difficulty": 4, "type": "mcq" as const, "text": "To improve his health, he started exercising regularly and eating more vegetables. He felt much better after a few weeks.", "question": "What did he start doing to improve his health?", "options": ["Eating more meat", "Exercising regularly and eating vegetables", "Sleeping more", "Working harder"], "answer": "Exercising regularly and eating vegetables" },
            { "id": "en-read-4-4", "difficulty": 4, "type": "mcq" as const, "text": "Because of the traffic jam, they arrived late for the meeting. They had to apologize to everyone for the delay.", "question": "Why were they late for the meeting?", "options": ["Because of the rain", "Because of the snow", "Because of the traffic jam", "Because of the accident"], "answer": "Because of the traffic jam" },
            // Difficulty 5 (4 questions)
            { "id": "en-read-5-1", "difficulty": 5, "type": "mcq" as const, "text": "The scientist hypothesized that the new drug would significantly reduce symptoms. Initial results from the clinical trial are promising.", "question": "What is the clinical trial testing?", "options": ["A new exercise", "A new diet", "A new drug", "A new therapy"], "answer": "A new drug" },
            { "id": "en-read-5-2", "difficulty": 5, "type": "mcq" as const, "text": "Despite the company's innovative approach, they faced considerable challenges in market penetration due to established competitors.", "question": "Why did the company face challenges?", "options": ["Lack of innovation", "Strong market demand", "Established competitors", "Government regulations"], "answer": "Established competitors" },
            { "id": "en-read-5-3", "difficulty": 5, "type": "mcq" as const, "text": "Archaeologists discovered ancient artifacts suggesting a sophisticated civilization existed there centuries ago. The findings are under careful examination.", "question": "What did archaeologists discover?", "options": ["Modern tools", "Ancient artifacts", "New buildings", "Fossilized plants"], "answer": "Ancient artifacts" },
            { "id": "en-read-5-4", "difficulty": 5, "type": "mcq" as const, "text": "Environmentalists are advocating for stricter regulations to combat deforestation. They emphasize the long-term ecological consequences.", "question": "What are environmentalists advocating for?", "options": ["More deforestation", "Looser regulations", "Stricter regulations", "Less ecological awareness"], "answer": "Stricter regulations" },
            // Difficulty 6 (4 questions)
            { "id": "en-read-6-1", "difficulty": 6, "type": "mcq" as const, "text": "The philosophical debate about free will versus determinism continues to intrigue scholars. No definitive conclusion has been universally accepted.", "question": "What is the subject of the philosophical debate?", "options": ["Economic policy", "Climate change", "Free will versus determinism", "Ancient history"], "answer": "Free will versus determinism" },
            { "id": "en-read-6-2", "difficulty": 6, "type": "mcq" as const, "text": "Quantum entanglement, a phenomenon in physics, describes a state where particles are linked regardless of distance. This concept challenges classical physics.", "question": "What concept challenges classical physics?", "options": ["Gravity", "Electromagnetism", "Quantum entanglement", "Thermodynamics"], "answer": "Quantum entanglement" },
            { "id": "en-read-6-3", "difficulty": 6, "type": "mcq" as const, "text": "The economic recession led to a significant downturn in the stock market. Investors are wary and financial analysts predict slow recovery.", "question": "What caused a downturn in the stock market?", "options": ["Political elections", "Technological innovation", "Economic recession", "Natural disasters"], "answer": "Economic recession" },
            { "id": "en-read-6-4", "difficulty": 6, "type": "mcq" as const, "text": "Genetic engineering holds immense potential for treating diseases. However, ethical considerations regarding its application are hotly debated.", "question": "What is hotly debated regarding genetic engineering?", "options": ["Its cost-effectiveness", "Its complexity", "Ethical considerations", "Its popularity"], "answer": "Ethical considerations" }
        ],
        "listening": [
            // Difficulty 1 (4 questions)
            { "id": "en-listen-1-1", "difficulty": 1, "type": "listening", "text": "The sun is shining.", "question": "What is the weather like?", "options": ["Rainy", "Cloudy", "Sunny", "Snowy"], "answer": "Sunny" },
            { "id": "en-listen-1-2", "difficulty": 1, "type": "listening", "text": "I have a blue shirt.", "question": "What color is my shirt?", "options": ["Red", "Blue", "Green", "Yellow"], "answer": "Blue" },
            { "id": "en-listen-1-3", "difficulty": 1, "type": "listening", "text": "The dog is barking.", "question": "What animal is making noise?", "options": ["Cat", "Bird", "Dog", "Cow"], "answer": "Dog" },
            { "id": "en-listen-1-4", "difficulty": 1, "type": "listening", "text": "I drink milk in the morning.", "question": "When do I drink milk?", "options": ["In the evening", "At noon", "In the morning", "At night"], "answer": "In the morning" },
            // Difficulty 2 (4 questions)
            { "id": "en-listen-2-1", "difficulty": 2, "type": "listening", "text": "She is reading a book.", "question": "What is she doing?", "options": ["Writing a letter", "Watching TV", "Reading a book", "Cooking dinner"], "answer": "Reading a book" },
            { "id": "en-listen-2-2", "difficulty": 2, "type": "listening", "text": "He is playing the piano.", "question": "What instrument is he playing?", "options": ["Guitar", "Drums", "Piano", "Violin"], "answer": "Piano" },
            { "id": "en-listen-2-3", "difficulty": 2, "type": "listening", "text": "They are eating pizza.", "question": "What food are they eating?", "options": ["Salad", "Soup", "Pizza", "Pasta"], "answer": "Pizza" },
            { "id": "en-listen-2-4", "difficulty": 2, "type": "listening", "text": "We are going to the park.", "question": "Where are we going?", "options": ["To the beach", "To the zoo", "To the park", "To the cinema"], "answer": "To the park" },
            // Difficulty 3 (4 questions)
            { "id": "en-listen-3-1", "difficulty": 3, "type": "listening", "text": "The cat jumped over the fence.", "question": "What did the cat jump over?", "options": ["The wall", "The car", "The fence", "The tree"], "answer": "The fence" },
            { "id": "en-listen-3-2", "difficulty": 3, "type": "listening", "text": "She bought bread and cheese at the market.", "question": "Where did she buy bread and cheese?", "options": ["At the library", "At the bakery", "At the market", "At the cinema"], "answer": "At the market" },
            { "id": "en-listen-3-3", "difficulty": 3, "type": "listening", "text": "He is studying for his English test.", "question": "What test is he studying for?", "options": ["Math test", "Science test", "English test", "History test"], "answer": "English test" },
            { "id": "en-listen-3-4", "difficulty": 3, "type": "listening", "text": "They decided to visit Italy next summer.", "question": "Where do they plan to visit next summer?", "options": ["France", "Spain", "Italy", "Germany"], "answer": "Italy" },
            // Difficulty 4 (4 questions)
            { "id": "en-listen-4-1", "difficulty": 4, "type": "listening", "text": "Despite the rain, the children played happily in the garden.", "question": "Where did the children play?", "options": ["Indoors", "In the park", "In the garden", "On the street"], "answer": "In the garden" },
            { "id": "en-listen-4-2", "difficulty": 4, "type": "listening", "text": "She carefully watered the plants in her balcony every morning.", "question": "Where does she water the plants?", "options": ["In the kitchen", "In the living room", "In her balcony", "In the bedroom"], "answer": "In her balcony" },
            { "id": "en-listen-4-3", "difficulty": 4, "type": "listening", "text": "He apologized for being late due to unexpected traffic.", "question": "Why was he late?", "options": ["Because of the weather", "Because of the train delay", "Because of unexpected traffic", "Because he overslept"], "answer": "Because of unexpected traffic" },
            { "id": "en-listen-4-4", "difficulty": 4, "type": "listening", "text": "They are planning to renovate their old house next year.", "question": "What are they planning to do with their house?", "options": ["Sell it", "Rent it", "Renovate it", "Demolish it"], "answer": "Renovate it" },
            // Difficulty 5 (4 questions)
            { "id": "en-listen-5-1", "difficulty": 5, "type": "listening", "text": "The professor explained the complexities of quantum physics in simple terms.", "question": "What subject did the professor explain?", "options": ["Classical mechanics", "Thermodynamics", "Quantum physics", "Electromagnetism"], "answer": "Quantum physics" },
            { "id": "en-listen-5-2", "difficulty": 5, "type": "listening", "text": "The company announced a merger with a larger corporation to expand its market share.", "question": "What did the company announce?", "options": ["Bankruptcy", "Layoffs", "A merger", "New product launch"], "answer": "A merger" },
            { "id": "en-listen-5-3", "difficulty": 5, "type": "listening", "text": "Despite initial skepticism, the new technology proved to be remarkably efficient.", "question": "What was proven to be remarkably efficient?", "options": ["Old methods", "Traditional tools", "New technology", "Existing systems"], "answer": "New technology" },
            { "id": "en-listen-5-4", "difficulty": 5, "type": "listening", "text": "The environmental impact assessment is crucial before starting the construction project.", "question": "What assessment is crucial before construction?", "options": ["Financial assessment", "Environmental impact assessment", "Risk assessment", "Technical assessment"], "answer": "Environmental impact assessment" },
            // Difficulty 6 (4 questions)
            { "id": "en-listen-6-1", "difficulty": 6, "type": "listening", "text": "The geopolitical implications of the treaty are far-reaching and complex.", "question": "What are far-reaching and complex?", "options": ["Economic benefits", "Military strategies", "Geopolitical implications", "Cultural exchanges"], "answer": "Geopolitical implications" },
            { "id": "en-listen-6-2", "difficulty": 6, "type": "listening", "text": "Her nuanced understanding of historical contexts enriched her analysis.", "question": "What enriched her analysis?", "options": ["Personal opinions", "Limited data", "Nuanced understanding of historical contexts", "Popular beliefs"], "answer": "Nuanced understanding of historical contexts" },
            { "id": "en-listen-6-3", "difficulty": 6, "type": "listening", "text": "The ethical dilemmas posed by artificial intelligence are increasingly pertinent.", "question": "What is increasingly pertinent?", "options": ["Benefits of AI", "Technical challenges of AI", "Ethical dilemmas posed by AI", "Public interest in AI"], "answer": "Ethical dilemmas posed by AI" },
            { "id": "en-listen-6-4", "difficulty": 6, "type": "listening", "text": "The sociological ramifications of rapid urbanization require careful consideration.", "question": "What requires careful consideration?", "options": ["Benefits of urbanization", "Speed of development", "Sociological ramifications of urbanization", "Economic growth from urbanization"], "answer": "Sociological ramifications of urbanization" }
        ],
        "speaking": [
                // Difficulty 1 (4 questions)
                { "id": "en-speak-1-1", "difficulty": 1, "type": "text", "text": "Greetings. It's a pleasure to acknowledge your presence.", "referenceText": "Hello." },
                { "id": "en-speak-1-2", "difficulty": 1, "type": "text", "text": "I express my gratitude for your assistance.", "referenceText": "Thank you." },
                { "id": "en-speak-1-3", "difficulty": 1, "type": "text", "text": "I bid you a fond farewell.", "referenceText": "Good bye." },
                { "id": "en-speak-1-4", "difficulty": 1, "type": "text", "text": "I accept your offer with enthusiasm.", "referenceText": "Yes, please." },
                // Difficulty 2 (4 questions)
                { "id": "en-speak-2-1", "difficulty": 2, "type": "text", "text": "I am doing well, thank you for asking.", "referenceText": "How are you?" },
                { "id": "en-speak-2-2", "difficulty": 2, "type": "text", "text": "This is a book.", "referenceText": "What is this?" },
                { "id": "en-speak-2-3", "difficulty": 2, "type": "text", "text": "It is a pleasure to make your acquaintance.", "referenceText": "Nice to meet you." },
                { "id": "en-speak-2-4", "difficulty": 2, "type": "text", "text": "I will see you again in the future.", "referenceText": "See you later." },
                // Difficulty 3 (4 questions)
                { "id": "en-speak-3-1", "difficulty": 3, "type": "text", "text": "I reside in the city of São Paulo.", "referenceText": "Where do you live?" },
                { "id": "en-speak-3-2", "difficulty": 3, "type": "text", "text": "The current time is three o'clock.", "referenceText": "What time is it?" },
                { "id": "en-speak-3-3", "difficulty": 3, "type": "text", "text": "I find the shade of blue to be quite appealing.", "referenceText": "I like this color." },
                { "id": "en-speak-3-4", "difficulty": 3, "type": "text", "text": "I request your assistance with this task.", "referenceText": "Can you help me?" },
                // Difficulty 4 (4 questions)
                { "id": "en-speak-4-1", "difficulty": 4, "type": "text", "text": "My hobbies include reading, hiking, and playing the guitar.", "referenceText": "What are your hobbies?" },
                { "id": "en-speak-4-2", "difficulty": 4, "type": "text", "text": "My family consists of my parents, two siblings, and a pet dog.", "referenceText": "Tell me about your family." },
                { "id": "en-speak-4-3", "difficulty": 4, "type": "text", "text": "My hometown is a small, quiet town with friendly residents and beautiful parks.", "referenceText": "Describe your hometown." },
                { "id": "en-speak-4-4", "difficulty": 4, "type": "text", "text": "Today, I worked on a project, went to the gym, and had dinner with friends.", "referenceText": "What did you do today?" },
                // Difficulty 5 (4 questions)
                { "id": "en-speak-5-1", "difficulty": 5, "type": "text", "text": "Regular exercise improves cardiovascular health, boosts mood, and increases energy levels.", "referenceText": "Explain the benefits of exercise." },
                { "id": "en-speak-5-2", "difficulty": 5, "type": "text", "text": "I particularly enjoy science fiction movies for their imaginative stories and special effects.", "referenceText": "Discuss your favorite type of movie." },
                { "id": "en-speak-5-3", "difficulty": 5, "type": "text", "text": "A memorable trip to Japan involved exploring ancient temples and experiencing the unique culture.", "referenceText": "Describe a memorable travel experience." },
                { "id": "en-speak-5-4", "difficulty": 5, "type": "text", "text": "My career aspirations include becoming a leader in my field and contributing to innovative projects.", "referenceText": "What are your career aspirations?" },
                // Difficulty 6 (4 questions)
                { "id": "en-speak-6-1", "difficulty": 6, "type": "text", "text": "Social media has both positive and negative impacts, affecting communication, information dissemination, and mental health.", "referenceText": "Analyze the impact of social media on society." },
                { "id": "en-speak-6-2", "difficulty": 6, "type": "text", "text": "Globalization presents challenges such as economic inequality and cultural homogenization, but also offers opportunities for global cooperation.", "referenceText": "Discuss the challenges of globalization." },
                { "id": "en-speak-6-3", "difficulty": 6, "type": "text", "text": "Sustainable development involves balancing economic growth, social equity, and environmental protection for long-term well-being.", "referenceText": "Explain the principles of sustainable development." },
                { "id": "en-speak-6-4", "difficulty": 6, "type": "text", "text": "The ethics of artificial intelligence raise questions about autonomy, bias, and the potential impact on employment and society.", "referenceText": "Debate the ethics of artificial intelligence." }
        ],
        "grammar": [
             // Grammar questions - English
            // Difficulty 1 (4 questions) - Simple Present Tense
            { "id": "en-grammar-1-1", "difficulty": 1, "type": "mcq" as const, "question": "Choose the correct verb: He ____ (go) to school every day.", "options": ["go", "goes", "went", "going"], "answer": "goes" },
            { "id": "en-grammar-1-2", "difficulty": 1, "type": "mcq" as const, "question": "They ____ (play) football on weekends.", "options": ["play", "plays", "played", "playing"], "answer": "play" },
            { "id": "en-grammar-1-3", "difficulty": 1, "type": "mcq" as const, "question": "I ____ (be) a student.", "options": ["am", "is", "are", "be"], "answer": "am" },
            { "id": "en-grammar-1-4", "difficulty": 1, "type": "mcq" as const, "question": "She ____ (like) ice cream.", "options": ["like", "likes", "liked", "liking"], "answer": "likes" },
            // Difficulty 2 (4 questions) - Simple Past Tense
            { "id": "en-grammar-2-1", "difficulty": 2, "type": "mcq" as const, "question": "Yesterday, we ____ (watch) a movie.", "options": ["watch", "watches", "watched", "watching"], "answer": "watched" },
            { "id": "en-grammar-2-2", "difficulty": 2, "type": "mcq" as const, "question": "I ____ (eat) breakfast this morning.", "options": ["eat", "eats", "ate", "eating"], "answer": "ate" },
            { "id": "en-grammar-2-3", "difficulty": 2, "type": "mcq" as const, "question": "She ____ (buy) a new dress last week.", "options": ["buy", "buys", "bought", "buying"], "answer": "bought" },
            { "id": "en-grammar-2-4", "difficulty": 2, "type": "mcq" as const, "question": "They ____ (arrive) late for the party.", "options": ["arrive", "arrives", "arrived", "arriving"], "answer": "arrived" },
            // Difficulty 3 (4 questions) - Present Continuous Tense
            { "id": "en-grammar-3-1", "difficulty": 3, "type": "mcq" as const, "question": "Right now, he ____ (work).", "options": ["work", "works", "worked", "is working"], "answer": "is working" },
            { "id": "en-grammar-3-2", "difficulty": 3, "type": "mcq" as const, "question": "We ____ (study) for the exam at the moment.", "options": ["study", "studies", "studied", "are studying"], "answer": "are studying" },
            { "id": "en-grammar-3-3", "difficulty": 3, "type": "mcq" as const, "question": "She ____ (cook) dinner in the kitchen.", "options": ["cook", "cooks", "cooked", "is cooking"], "answer": "is cooking" },
            { "id": "en-grammar-3-4", "difficulty": 3, "type": "mcq" as const, "question": "The children ____ (play) in the garden now.", "options": ["play", "plays", "played", "are playing"], "answer": "are playing" },
            // Difficulty 4 (4 questions) - Future Simple Tense (will)
            { "id": "en-grammar-4-1", "difficulty": 4, "type": "mcq" as const, "question": "I think it ____ (rain) tomorrow.", "options": ["rain", "rains", "rained", "will rain"], "answer": "will rain" },
            { "id": "en-grammar-4-2", "difficulty": 4, "type": "mcq" as const, "question": "They ____ (travel) to Europe next year.", "options": ["travel", "travels", "traveled", "will travel"], "answer": "will travel" },
            { "id": "en-grammar-4-3", "difficulty": 4, "type": "mcq" as const, "question": "She ____ (be) happy to see you.", "options": ["be", "is", "are", "will be"], "answer": "will be" },
            { "id": "en-grammar-4-4", "difficulty": 4, "type": "mcq" as const, "question": "We ____ (have) a meeting next week.", "options": ["have", "has", "had", "will have"], "answer": "will have" },
            // Difficulty 5 (4 questions) - Present Perfect Tense
            { "id": "en-grammar-5-1", "difficulty": 5, "type": "mcq" as const, "question": "I ____ (see) that movie before.", "options": ["see", "sees", "saw", "have seen"], "answer": "have seen" },
            { "id": "en-grammar-5-2", "difficulty": 5, "type": "mcq" as const, "question": "____ (you/ever/be) to Paris?", "options": ["Have you ever be", "Has you ever been", "Have you ever been", "You have ever been"], "answer": "Have you ever been" },
            { "id": "en-grammar-5-3", "difficulty": 5, "type": "mcq" as const, "question": "She ____ (finish) her work already.", "options": ["finish", "finishes", "finished", "has finished"], "answer": "has finished" },
            { "id": "en-grammar-5-4", "difficulty": 5, "type": "mcq" as const, "question": "They ____ (live) here for five years.", "options": ["live", "lives", "lived", "have lived"], "answer": "have lived" },
            // Difficulty 6 (4 questions) - Conditionals - First Conditional
            { "id": "en-grammar-6-1", "difficulty": 6, "type": "mcq" as const, "question": "If it ____ (rain), we will stay home.", "options": ["rain", "rains", "rained", "will rain"], "answer": "rains" },
            { "id": "en-grammar-6-2", "difficulty": 6, "type": "mcq" as const, "question": "If you study hard, you ____ (pass) the exam.", "options": ["pass", "passes", "passed", "will pass"], "answer": "will pass" },
            { "id": "en-grammar-6-3", "difficulty": 6, "type": "mcq" as const, "question": "She will be angry if he ____ (be) late.", "options": ["be", "is", "are", "will be"], "answer": "is" },
            { "id": "en-grammar-6-4", "difficulty": 6, "type": "mcq" as const, "question": "If they ____ (not hurry), they will miss the bus.", "options": ["not hurry", "don't hurry", "didn't hurry", "will not hurry"], "answer": "don't hurry" }
        ]
    },
"es": {
        "vocabulary": [
            // Difficulty 1 (4 questions)
            { "id": "es-vocab-1-1", "difficulty": 1, "type": "mcq" as const, "question": "Elige el sinónimo de 'grande'", "options": ["pequeño", "enorme", "diminuto", "corto"], "answer": "enorme" },
            { "id": "es-vocab-1-2", "difficulty": 1, "type": "mcq" as const, "question": "¿Qué significa 'frío'?", "options": ["temperatura alta", "temperatura baja", "temperatura templada", "temperatura normal"], "answer": "temperatura baja" },
            { "id": "es-vocab-1-3", "difficulty": 1, "type": "mcq" as const, "question": "Selecciona el opuesto de 'arriba'", "options": ["abajo", "alto", "cima", "encima"], "answer": "abajo" },
            { "id": "es-vocab-1-4", "difficulty": 1, "type": "mcq" as const, "question": "¿Qué palabra significa 'hacer una pregunta'?", "options": ["responder", "replicar", "preguntar", "decir"], "answer": "preguntar" },
            // Difficulty 2 (4 questions)
            { "id": "es-vocab-2-1", "difficulty": 2, "type": "mcq" as const, "question": "Elige el sinónimo de 'rápido'", "options": ["lento", "veloz", "ágil", "perezoso"], "answer": "veloz" },
            { "id": "es-vocab-2-2", "difficulty": 2, "type": "mcq" as const, "question": "¿Qué significa 'hermoso'?", "options": ["feo", "bonito", "simple", "casero"], "answer": "bonito" },
            { "id": "es-vocab-2-3", "difficulty": 2, "type": "mcq" as const, "question": "Selecciona el antónimo de 'fácil'", "options": ["sencillo", "difícil", "sin esfuerzo", "ligero"], "answer": "difícil" },
            { "id": "es-vocab-2-4", "difficulty": 2, "type": "mcq" as const, "question": "¿Qué palabra describe algo que ocurre cada día?", "options": ["semanal", "mensual", "diario", "anual"], "answer": "diario" },
            // Difficulty 3 (4 questions)
            { "id": "es-vocab-3-1", "difficulty": 3, "type": "mcq" as const, "question": "Elige el sinónimo de 'inteligente'", "options": ["tonto", "listo", "necio", "torpe"], "answer": "listo" },
            { "id": "es-vocab-3-2", "difficulty": 3, "type": "mcq" as const, "question": "¿Qué significa 'esencial'?", "options": ["innecesario", "importante", "opcional", "extra"], "answer": "importante" },
            { "id": "es-vocab-3-3", "difficulty": 3, "type": "mcq" as const, "question": "Selecciona el antónimo de 'generoso'", "options": ["amable", "egoísta", "caritativo", "benevolente"], "answer": "egoísta" },
            { "id": "es-vocab-3-4", "difficulty": 3, "type": "mcq" as const, "question": "¿Qué palabra describe un sentimiento de gran felicidad?", "options": ["tristeza", "alegría", "enojo", "miedo"], "answer": "alegría" },
            // Difficulty 4 (4 questions)
            { "id": "es-vocab-4-1", "difficulty": 4, "type": "mcq" as const, "question": "Elige el sinónimo de 'significativo'", "options": ["menor", "importante", "trivial", "despreciable"], "answer": "importante" },
            { "id": "es-vocab-4-2", "difficulty": 4, "type": "mcq" as const, "question": "¿Qué significa 'meticuloso'?", "options": ["descuidado", "detallado", "descuidado", "apresurado"], "answer": "detallado" },
            { "id": "es-vocab-4-3", "difficulty": 4, "type": "mcq" as const, "question": "Selecciona el antónimo de 'optimista'", "options": ["esperanzado", "pesimista", "positivo", "alegre"], "answer": "pesimista" },
            { "id": "es-vocab-4-4", "difficulty": 4, "type": "mcq" as const, "question": "¿Qué palabra significa 'mejorar algo'?", "options": ["empeorar", "dañar", "mejorar", "reducir"], "answer": "mejorar" },
            // Difficulty 5 (4 questions) - Falsos Cognados (Portuguese Speaker Focus) + True/False
            { "id": "es-vocab-5-1", "difficulty": 5, "type": "mcq" as const, "question": "Elige la mejor traducción para 'actually' en 'Actually, estoy cansado.'", "options": ["actualmente", "en realidad", "pretender", "fabricar"], "answer": "en realidad" },
            { "id": "es-vocab-5-2", "difficulty": 5, "type": "mcq" as const, "question": "¿Qué opción usa correctamente 'intend'?", "options": ["Yo pretendo ir a la fiesta.", "Yo intento ir a la fiesta.", "Yo fabrico ir a la fiesta.", "Yo realizo ir a la fiesta."], "answer": "Yo intento ir a la fiesta." },
            { "id": "es-vocab-5-3", "difficulty": 5, "type": "true_false", "statement": "Afirmación: 'Fabric' en inglés significa 'fábrica' en español.", "correctAnswer": false },
            { "id": "es-vocab-5-4", "difficulty": 5, "type": "true_false", "statement": "Afirmación: 'Realize' en inglés usualmente se traduce como 'realizar' en español.", "correctAnswer": false },
            // Difficulty 6 (4 questions) - Falsos Cognados Difíciles + True/False
            { "id": "es-vocab-6-1", "difficulty": 6, "type": "mcq" as const, "question": "Selecciona la mejor traducción al español para 'successful' en 'Él fue un hombre de negocios successful.'", "options": ["sucessoso", "exitoso", "afortunado", "consecutivos"], "answer": "exitoso" },
            { "id": "es-vocab-6-2", "difficulty": 6, "type": "mcq" as const, "question": "¿Qué oración usa correctamente la palabra en inglés 'sensible' (en el sentido de 'razonable')?", "options": ["Él es una persona sensible, él siente todo.", "Él tomó una decisión sensible de quedarse en casa durante la tormenta.", "El vestido es muy sensible, puedes tocarlo.", "Ella es sensible a la luz solar."], "answer": "Él tomó una decisión sensible de quedarse en casa durante la tormenta." },
            { "id": "es-vocab-6-3", "difficulty": 6, "type": "true_false", "statement": "Afirmación: 'Costume' en inglés, cuando se refiere a ropa, significa 'costume' en español.", "correctAnswer": false },
            { "id": "es-vocab-6-4", "difficulty": 6, "type": "true_false", "statement": "Afirmación: 'Parents' en inglés se traduce como 'parientes' en español.", "correctAnswer": false }
        ],
        "reading": [
            // Difficulty 1 (4 questions)
            { "id": "es-read-1-1", "difficulty": 1, "type": "mcq" as const, "text": "El gato se sentó en la alfombra.", "question": "¿Dónde se sentó el gato?", "options": ["En la silla", "En el suelo", "En la alfombra", "En la mesa"], "answer": "En la alfombra" },
            { "id": "es-read-1-2", "difficulty": 1, "type": "mcq" as const, "text": "Los pájaros vuelan en el cielo.", "question": "¿Dónde vuelan los pájaros?", "options": ["En el mar", "En el suelo", "En el cielo", "En los árboles"], "answer": "En el cielo" },
            { "id": "es-read-1-3", "difficulty": 1, "type": "mcq" as const, "text": "Bebemos agua cuando tenemos sed.", "question": "¿Por qué bebemos agua?", "options": ["Cuando tenemos hambre", "Cuando tenemos sueño", "Cuando tenemos sed", "Cuando tenemos frío"], "answer": "Cuando tenemos sed" },
            { "id": "es-read-1-4", "difficulty": 1, "type": "mcq" as const, "text": "El libro está sobre la mesa.", "question": "¿Dónde está el libro?", "options": ["Debajo de la silla", "Sobre la mesa", "En la bolsa", "Junto a la cama"], "answer": "Sobre la mesa" },
            // Difficulty 2 (4 questions)
            { "id": "es-read-2-1", "difficulty": 2, "type": "mcq" as const, "text": "Ella tiene un coche rojo. El coche es muy rápido.", "question": "¿De qué color es su coche?", "options": ["Azul", "Rojo", "Verde", "Amarillo"], "answer": "Rojo" },
            { "id": "es-read-2-2", "difficulty": 2, "type": "mcq" as const, "text": "Él juega al fútbol en el parque todos los domingos. Lo disfruta mucho.", "question": "¿Cuándo juega al fútbol?", "options": ["Todos los lunes", "Todos los sábados", "Todos los domingos", "Todos los viernes"], "answer": "Todos los domingos" },
            { "id": "es-read-2-3", "difficulty": 2, "type": "mcq" as const, "text": "Viven en una casa pequeña. Tiene dos dormitorios y un jardín.", "question": "¿Cuántos dormitorios tiene su casa?", "options": ["Uno", "Dos", "Tres", "Cuatro"], "answer": "Dos" },
            { "id": "es-read-2-4", "difficulty": 2, "type": "mcq" as const, "text": "El tiempo hoy está soleado y cálido. Mucha gente está en la playa.", "question": "¿Cómo está el tiempo hoy?", "options": ["Nublado y frío", "Lluvioso y ventoso", "Soleado y cálido", "Tormentoso y húmedo"], "answer": "Soleado y cálido" },
            // Difficulty 3 (4 questions)
            { "id": "es-read-3-1", "difficulty": 3, "type": "mcq" as const, "text": "Aunque estaba lloviendo, fueron a caminar. Llevaron paraguas con ellos.", "question": "¿Por qué llevaron paraguas?", "options": ["Porque estaba soleado", "Porque estaba nevando", "Porque estaba lloviendo", "Porque hacía viento"], "answer": "Porque estaba lloviendo" },
            { "id": "es-read-3-2", "difficulty": 3, "type": "mcq" as const, "text": "El profesor pidió a los estudiantes que leyeran el capítulo tres para la tarea. Deberían estar listos para discutirlo en clase mañana.", "question": "¿Qué deben leer los estudiantes para la tarea?", "options": ["Capítulo uno", "Capítulo dos", "Capítulo tres", "Capítulo cuatro"], "answer": "Capítulo tres" },
            { "id": "es-read-3-3", "difficulty": 3, "type": "mcq" as const, "text": "Ella quería hornear un pastel, pero no tenía huevos. Así que, fue a la tienda a comprar algunos.", "question": "¿Por qué fue a la tienda?", "options": ["Para comprar leche", "Para comprar harina", "Para comprar huevos", "Para comprar azúcar"], "answer": "Para comprar huevos" },
            { "id": "es-read-3-4", "difficulty": 3, "type": "mcq" as const, "text": "Después de terminar el trabajo, decidió relajarse viendo una película. Hizo palomitas de maíz y se sentó en el sofá.", "question": "¿Qué decidió hacer después del trabajo?", "options": ["Ir a correr", "Leer un libro", "Ver una película", "Cocinar la cena"], "answer": "Ver una película" },
            // Difficulty 4 (4 questions)
            { "id": "es-read-4-1", "difficulty": 4, "type": "mcq" as const, "text": "A pesar de sentirse cansada, completó su proyecto. Se quedó despierta hasta tarde para asegurarse de que todo fuera perfecto.", "question": "¿Por qué se quedó despierta hasta tarde?", "options": ["Porque estaba aburrida", "Para ver la televisión", "Para completar su proyecto", "Para limpiar la casa"], "answer": "Para completar su proyecto" },
            { "id": "es-read-4-2", "difficulty": 4, "type": "mcq" as const, "text": "La vieja casa se alzaba en una colina con vistas al pueblo. Había estado vacía durante muchos años y estaba rodeada de altos árboles.", "question": "¿Dónde estaba ubicada la vieja casa?", "options": ["En el centro del pueblo", "Junto al río", "En una colina", "En el valle"], "answer": "En una colina" },
            { "id": "es-read-4-3", "difficulty": 4, "type": "mcq" as const, "text": "Para mejorar su salud, comenzó a hacer ejercicio regularmente y a comer más verduras. Se sintió mucho mejor después de algunas semanas.", "question": "¿Qué comenzó a hacer para mejorar su salud?", "options": ["Comer más carne", "Hacer ejercicio regularmente y comer verduras", "Dormir más", "Trabajar más duro"], "answer": "Hacer ejercicio regularmente y comer verduras" },
            { "id": "es-read-4-4", "difficulty": 4, "type": "mcq" as const, "text": "Debido al atasco, llegaron tarde a la reunión. Tuvieron que disculparse con todos por la demora.", "question": "¿Por qué llegaron tarde a la reunión?", "options": ["Debido a la lluvia", "Debido a la nieve", "Debido al atasco", "Debido al accidente"], "answer": "Debido al atasco" },
            // Difficulty 5 (4 questions)
            { "id": "es-read-5-1", "difficulty": 5, "type": "mcq" as const, "text": "El científico planteó la hipótesis de que el nuevo fármaco reduciría significativamente los síntomas. Los resultados iniciales del ensayo clínico son prometedores.", "question": "¿Qué está probando el ensayo clínico?", "options": ["Un nuevo ejercicio", "Una nueva dieta", "Un nuevo fármaco", "Una nueva terapia"], "answer": "Un nuevo fármaco" },
            { "id": "es-read-5-2", "difficulty": 5, "type": "mcq" as const, "text": "A pesar del enfoque innovador de la empresa, enfrentaron considerables desafíos en la penetración del mercado debido a competidores establecidos.", "question": "¿Por qué la empresa enfrentó desafíos?", "options": ["Falta de innovación", "Fuerte demanda del mercado", "Competidores establecidos", "Regulaciones gubernamentales"], "answer": "Competidores establecidos" },
            { "id": "es-read-5-3", "difficulty": 5, "type": "mcq" as const, "text": "Los arqueólogos descubrieron artefactos antiguos que sugieren que existió una civilización sofisticada hace siglos. Los hallazgos están bajo cuidadoso examen.", "question": "¿Qué descubrieron los arqueólogos?", "options": ["Herramientas modernas", "Artefactos antiguos", "Nuevos edificios", "Plantas fosilizadas"], "answer": "Artefactos antiguos" },
            { "id": "es-read-5-4", "difficulty": 5, "type": "mcq" as const, "text": "Los ambientalistas están abogando por regulaciones más estrictas para combatir la deforestación. Enfatizan las consecuencias ecológicas a largo plazo.", "question": "¿Por qué abogan los ambientalistas?", "options": ["Más deforestación", "Regulaciones más laxas", "Regulaciones más estrictas", "Menos conciencia ecológica"], "answer": "Regulaciones más estrictas" },
            // Difficulty 6 (4 questions)
            { "id": "es-read-6-1", "difficulty": 6, "type": "mcq" as const, "text": "El debate filosófico sobre el libre albedrío versus el determinismo sigue intrigando a los académicos. No se ha aceptado universalmente ninguna conclusión definitiva.", "question": "¿Cuál es el tema del debate filosófico?", "options": ["Política económica", "Cambio climático", "Libre albedrío versus determinismo", "Historia antigua"], "answer": "Libre albedrío versus determinismo" },
            { "id": "es-read-6-2", "difficulty": 6, "type": "mcq" as const, "text": "El entrelazamiento cuántico, un fenómeno en la física, describe un estado donde las partículas están vinculadas sin importar la distancia. Este concepto desafía la física clásica.", "question": "¿Qué concepto desafía la física clásica?", "options": ["Gravedad", "Electromagnetismo", "Entrelazamiento cuántico", "Termodinámica"], "answer": "Entrelazamiento cuántico" },
            { "id": "es-read-6-3", "difficulty": 6, "type": "mcq" as const, "text": "La recesión económica provocó una disminución significativa en el mercado de valores. Los inversores se muestran cautelosos y los analistas financieros predicen una recuperación lenta.", "question": "¿Qué causó una disminución en el mercado de valores?", "options": ["Elecciones políticas", "Innovación tecnológica", "Recesión económica", "Desastres naturales"], "answer": "Recesión económica" },
            { "id": "es-read-6-4", "difficulty": 6, "type": "mcq" as const, "text": "La ingeniería genética tiene un inmenso potencial para tratar enfermedades. Sin embargo, las consideraciones éticas con respecto a su aplicación son muy debatidas.", "question": "¿Qué es muy debatido con respecto a la ingeniería genética?", "options": ["Su rentabilidad", "Su complejidad", "Consideraciones éticas", "Su popularidad"], "answer": "Consideraciones éticas" }
        ],"listening": [
            // Difficulty 1 (4 questions)
            { "id": "es-listen-1-1", "difficulty": 1, "type": "listening", "text": "El sol está brillando.", "question": "¿Qué tiempo hace?", "options": ["Lluvioso", "Nublado", "Soleado", "Nevado"], "answer": "Soleado" },
            { "id": "es-listen-1-2", "difficulty": 1, "type": "listening", "text": "Tengo una camisa azul.", "question": "¿De qué color es mi camisa?", "options": ["Roja", "Azul", "Verde", "Amarilla"], "answer": "Azul" },
            { "id": "es-listen-1-3", "difficulty": 1, "type": "listening", "text": "El perro está ladrando.", "question": "¿Qué animal está haciendo ruido?", "options": ["Gato", "Pájaro", "Perro", "Vaca"], "answer": "Perro" },
            { "id": "es-listen-1-4", "difficulty": 1, "type": "listening", "text": "Bebo leche por la mañana.", "question": "¿Cuándo bebo leche?", "options": ["Por la tarde", "Al mediodía", "Por la mañana", "Por la noche"], "answer": "Por la mañana" },
            // Difficulty 2 (4 questions)
            { "id": "es-listen-2-1", "difficulty": 2, "type": "listening", "text": "Ella está leyendo un libro.", "question": "¿Qué está haciendo ella?", "options": ["Escribiendo una carta", "Viendo televisión", "Leyendo un libro", "Cocinando la cena"], "answer": "Leyendo un libro" },
            { "id": "es-listen-2-2", "difficulty": 2, "type": "listening", "text": "Él está tocando el piano.", "question": "¿Qué instrumento está tocando él?", "options": ["Guitarra", "Batería", "Piano", "Violín"], "answer": "Piano" },
            { "id": "es-listen-2-3", "difficulty": 2, "type": "listening", "text": "Ellos están comiendo pizza.", "question": "¿Qué comida están comiendo ellos?", "options": ["Ensalada", "Sopa", "Pizza", "Pasta"], "answer": "Pizza" },
            { "id": "es-listen-2-4", "difficulty": 2, "type": "listening", "text": "Vamos a ir al parque.", "question": "¿A dónde vamos a ir?", "options": ["A la playa", "Al zoológico", "Al parque", "Al cine"], "answer": "Al parque" },
            // Difficulty 3 (4 questions)
            { "id": "es-listen-3-1", "difficulty": 3, "type": "listening", "text": "El gato saltó sobre la valla.", "question": "¿Sobre qué saltó el gato?", "options": ["La pared", "El coche", "La valla", "El árbol"], "answer": "La valla" },
            { "id": "es-listen-3-2", "difficulty": 3, "type": "listening", "text": "Ella compró pan y queso en el mercado.", "question": "¿Dónde compró ella pan y queso?", "options": ["En la biblioteca", "En la panadería", "En el mercado", "En el cine"], "answer": "En el mercado" },
            { "id": "es-listen-3-3", "difficulty": 3, "type": "listening", "text": "Él está estudiando para su examen de inglés.", "question": "¿Para qué examen está estudiando él?", "options": ["Examen de matemáticas", "Examen de ciencias", "Examen de inglés", "Examen de historia"], "answer": "Examen de inglés" },
            { "id": "es-listen-3-4", "difficulty": 3, "type": "listening", "text": "Ellos decidieron visitar Italia el próximo verano.", "question": "¿Dónde planean visitar el próximo verano?", "options": ["Francia", "España", "Italia", "Alemania"], "answer": "Italia" },
            // Difficulty 4 (4 questions)
            { "id": "es-listen-4-1", "difficulty": 4, "type": "listening", "text": "A pesar de la lluvia, los niños jugaron felizmente en el jardín.", "question": "¿Dónde jugaron los niños?", "options": ["En el interior", "En el parque", "En el jardín", "En la calle"], "answer": "En el jardín" },
            { "id": "es-listen-4-2", "difficulty": 4, "type": "listening", "text": "Ella regó cuidadosamente las plantas en su balcón cada mañana.", "question": "¿Dónde riega ella las plantas?", "options": ["En la cocina", "En la sala de estar", "En su balcón", "En el dormitorio"], "answer": "En su balcón" },
            { "id": "es-listen-4-3", "difficulty": 4, "type": "listening", "text": "Él se disculpó por llegar tarde debido al tráfico inesperado.", "question": "¿Por qué llegó tarde él?", "options": ["Debido al clima", "Debido al retraso del tren", "Debido al tráfico inesperado", "Porque se quedó dormido"], "answer": "Debido al tráfico inesperado" },
            { "id": "es-listen-4-4", "difficulty": 4, "type": "listening", "text": "Ellos están planeando renovar su vieja casa el próximo año.", "question": "¿Qué planean hacer ellos con su casa?", "options": ["Venderla", "Alquilarla", "Renovarla", "Demolerla"], "answer": "Renovarla" },
            // Difficulty 5 (4 questions)
            { "id": "es-listen-5-1", "difficulty": 5, "type": "listening", "text": "El profesor explicó las complejidades de la física cuántica en términos sencillos.", "question": "¿Qué tema explicó el profesor?", "options": ["Mecánica clásica", "Termodinámica", "Física cuántica", "Electromagnetismo"], "answer": "Física cuántica" },
            { "id": "es-listen-5-2", "difficulty": 5, "type": "listening", "text": "La compañía anunció una fusión con una corporación más grande para expandir su cuota de mercado.", "question": "¿Qué anunció la compañía?", "options": ["Bancarrota", "Despidos", "Una fusión", "Lanzamiento de nuevo producto"], "answer": "Una fusión" },
            { "id": "es-listen-5-3", "difficulty": 5, "type": "listening", "text": "A pesar del escepticismo inicial, la nueva tecnología demostró ser notablemente eficiente.", "question": "¿Qué se demostró que era notablemente eficiente?", "options": ["Viejos métodos", "Herramientas tradicionales", "Nueva tecnología", "Sistemas existentes"], "answer": "Nueva tecnología" },
            { "id": "es-listen-5-4", "difficulty": 5, "type": "listening", "text": "La evaluación de impacto ambiental es crucial antes de comenzar el proyecto de construcción.", "question": "¿Qué evaluación es crucial antes de la construcción?", "options": ["Evaluación financiera", "Evaluación de impacto ambiental", "Evaluación de riesgos", "Evaluación técnica"], "answer": "Evaluación de impacto ambiental" },
            // Difficulty 6 (4 questions)
            { "id": "es-listen-6-1", "difficulty": 6, "type": "listening", "text": "Las implicaciones geopolíticas del tratado son de gran alcance y complejas.", "question": "¿Qué son de gran alcance y complejas?", "options": ["Beneficios económicos", "Estrategias militares", "Implicaciones geopolíticas", "Intercambios culturales"], "answer": "Implicaciones geopolíticas" },
            { "id": "es-listen-6-2", "difficulty": 6, "type": "listening", "text": "Su comprensión matizada de los contextos históricos enriqueció su análisis.", "question": "¿Qué enriqueció su análisis?", "options": ["Opiniones personales", "Datos limitados", "Comprensión matizada de contextos históricos", "Creencias populares"], "answer": "Comprensión matizada de contextos históricos" },
            { "id": "es-listen-6-3", "difficulty": 6, "type": "listening", "text": "Los dilemas éticos planteados por la inteligencia artificial son cada vez más pertinentes.", "question": "¿Qué es cada vez más pertinente?", "options": ["Beneficios de la IA", "Desafíos técnicos de la IA", "Dilemas éticos planteados por la IA", "Interés público en la IA"], "answer": "Dilemas éticos planteados por la IA" },
            { "id": "es-listen-6-4", "difficulty": 6, "type": "listening", "text": "Las ramificaciones sociológicas de la rápida urbanización requieren una cuidadosa consideración.", "question": "¿Qué requiere una cuidadosa consideración?", "options": ["Beneficios de la urbanización", "Velocidad del desarrollo", "Ramificaciones sociológicas de la urbanización", "Crecimiento económico de la urbanización"], "answer": "Ramificaciones sociológicas de la urbanización" }
        ],
        "speaking": [
            // Difficulty 1 (4 questions)
            { "id": "es-speak-1-1", "difficulty": 1, "type": "text", "text": "Un saludo cordial. Es un placer reconocer tu presencia.", "referenceText": "Hola." },
            { "id": "es-speak-1-2", "difficulty": 1, "type": "text", "text": "Expreso mi gratitud por tu ayuda.", "referenceText": "Gracias." },
            { "id": "es-speak-1-3", "difficulty": 1, "type": "text", "text": "Te deseo una buena despedida.", "referenceText": "Adiós." },
            { "id": "es-speak-1-4", "difficulty": 1, "type": "text", "text": "Acepto tu oferta con entusiasmo.", "referenceText": "Sí, por favor." },
            // Difficulty 2 (4 questions)
            { "id": "es-speak-2-1", "difficulty": 2, "type": "text", "text": "Me encuentro bien, gracias por preguntar.", "referenceText": "¿Cómo estás?" },
            { "id": "es-speak-2-2", "difficulty": 2, "type": "text", "text": "Esto es un libro.", "referenceText": "¿Qué es esto?" },
            { "id": "es-speak-2-3", "difficulty": 2, "type": "text", "text": "Es un placer conocerte.", "referenceText": "Mucho gusto." },
            { "id": "es-speak-2-4", "difficulty": 2, "type": "text", "text": "Nos veremos en el futuro.", "referenceText": "Hasta luego." },
            // Difficulty 3 (4 questions)
            { "id": "es-speak-3-1", "difficulty": 3, "type": "text", "text": "Resido en la ciudad de Madrid.", "referenceText": "¿Dónde vives?" },
            { "id": "es-speak-3-2", "difficulty": 3, "type": "text", "text": "La hora actual es la una de la tarde.", "referenceText": "¿Qué hora es?" },
            { "id": "es-speak-3-3", "difficulty": 3, "type": "text", "text": "Encuentro muy atractivo el tono del rojo.", "referenceText": "Me gusta este color." },
            { "id": "es-speak-3-4", "difficulty": 3, "type": "text", "text": "Solicito tu asistencia con esta tarea.", "referenceText": "¿Puedes ayudarme?" },
            // Difficulty 4 (4 questions)
            { "id": "es-speak-4-1", "difficulty": 4, "type": "text", "text": "Mis pasatiempos incluyen la lectura, el senderismo y tocar el piano.", "referenceText": "¿Cuáles son tus hobbies?" },
            { "id": "es-speak-4-2", "difficulty": 4, "type": "text", "text": "Mi familia está compuesta por mis padres, tres hermanos y un gato mascota.", "referenceText": "Háblame de tu familia." },
            { "id": "es-speak-4-3", "difficulty": 4, "type": "text", "text": "Mi ciudad natal es un pueblo pequeño y tranquilo con habitantes amables y parques hermosos.", "referenceText": "Describe tu ciudad natal." },
            { "id": "es-speak-4-4", "difficulty": 4, "type": "text", "text": "Hoy, trabajé en un proyecto, fui al gimnasio y cené con amigos.", "referenceText": "¿Qué hiciste hoy?" },
            // Difficulty 5 (4 questions)
            { "id": "es-speak-5-1", "difficulty": 5, "type": "text", "text": "El ejercicio regular mejora la salud cardiovascular, eleva el estado de ánimo y aumenta los niveles de energía.", "referenceText": "Explica los beneficios del ejercicio." },
            { "id": "es-speak-5-2", "difficulty": 5, "type": "text", "text": "Disfruto particularmente de las películas de drama por sus historias emotivas y sus personajes complejos.", "referenceText": "Habla de tu tipo de película favorito." },
            { "id": "es-speak-5-3", "difficulty": 5, "type": "text", "text": "Un viaje memorable a Italia incluyó explorar ruinas antiguas y experimentar la rica cultura.", "referenceText": "Describe una experiencia de viaje memorable." },
            { "id": "es-speak-5-4", "difficulty": 5, "type": "text", "text": "Mis aspiraciones profesionales incluyen convertirme en un líder en mi campo y contribuir a proyectos innovadores.", "referenceText": "¿Cuáles son tus aspiraciones profesionales?" },
            // Difficulty 6 (4 questions)
            { "id": "es-speak-6-1", "difficulty": 6, "type": "text", "text": "Las redes sociales tienen impactos tanto positivos como negativos, afectando la comunicación, la difusión de información y la salud mental.", "referenceText": "Analiza el impacto de las redes sociales en la sociedad." },
            { "id": "es-speak-6-2", "difficulty": 6, "type": "text", "text": "La globalización presenta desafíos como la desigualdad económica y la homogeneización cultural, pero también ofrece oportunidades para la cooperación global.", "referenceText": "Discute los desafíos de la globalización." },
            { "id": "es-speak-6-3", "difficulty": 6, "type": "text", "text": "El desarrollo sostenible implica equilibrar el crecimiento económico, la equidad social y la protección ambiental para el bienestar a largo plazo.", "referenceText": "Explica los principios del desarrollo sostenible." },
            { "id": "es-speak-6-4", "difficulty": 6, "type": "text", "text": "La ética de la inteligencia artificial plantea preguntas sobre la autonomía, el sesgo y el impacto potencial en el empleo y la sociedad.", "referenceText": "Debate la ética de la inteligencia artificial." }
        ],
        "grammar": [
            // Grammar questions - Spanish
            // Difficulty 1 (4 questions) - Presente Simple
            { "id": "es-grammar-1-1", "difficulty": 1, "type": "mcq" as const, "question": "Elige el verbo correcto: Yo ____ (ser) estudiante.", "options": ["soy", "eres", "es", "somos"], "answer": "soy" },
            { "id": "es-grammar-1-2", "difficulty": 1, "type": "mcq" as const, "question": "Tú ____ (tener) un libro.", "options": ["tengo", "tienes", "tiene", "tenemos"], "answer": "tienes" },
            { "id": "es-grammar-1-3", "difficulty": 1, "type": "mcq" as const, "question": "Él ____ (comer) fruta.", "options": ["como", "comes", "come", "comemos"], "answer": "come" },
            { "id": "es-grammar-1-4", "difficulty": 1, "type": "mcq" as const, "question": "Nosotros ____ (vivir) aquí.", "options": ["vivo", "vives", "vive", "vivimos"], "answer": "vivimos" },
            // Difficulty 2 (4 questions) - Pretérito Indefinido
            { "id": "es-grammar-2-1", "difficulty": 2, "type": "mcq" as const, "question": "Ayer, yo ____ (ir) al cine.", "options": ["voy", "vas", "fue", "fui"], "answer": "fui" },
            { "id": "es-grammar-2-2", "difficulty": 2, "type": "mcq" as const, "question": "Tú ____ (ver) la televisión anoche.", "options": ["veo", "ves", "vio", "viste"], "answer": "viste" },
            { "id": "es-grammar-2-3", "difficulty": 2, "type": "mcq" as const, "question": "Ella ____ (comprar) un vestido nuevo.", "options": ["compro", "compras", "compró", "compramos"], "answer": "compró" },
            { "id": "es-grammar-2-4", "difficulty": 2, "type": "mcq" as const, "question": "Nosotros ____ (llegar) tarde.", "options": ["llego", "llegas", "llegamos", "llegaron"], "answer": "llegamos" },
            // Difficulty 3 (4 questions) - Presente Continuo
            { "id": "es-grammar-3-1", "difficulty": 3, "type": "mcq" as const, "question": "Ahora mismo, yo ____ (trabajar).", "options": ["trabajo", "trabajas", "trabajando", "estoy trabajando"], "answer": "estoy trabajando" },
            { "id": "es-grammar-3-2", "difficulty": 3, "type": "mcq" as const, "question": "Tú ____ (estudiar) para el examen ahora.", "options": ["estudio", "estudias", "estudiando", "estás estudiando"], "answer": "estás estudiando" },
            { "id": "es-grammar-3-3", "difficulty": 3, "type": "mcq" as const, "question": "Él ____ (cocinar) la cena.", "options": ["cocino", "cocinas", "cocinando", "está cocinando"], "answer": "está cocinando" },
            { "id": "es-grammar-3-4", "difficulty": 3, "type": "mcq" as const, "question": "Nosotros ____ (jugar) en el jardín.", "options": ["juego", "juegas", "jugando", "estamos jugando"], "answer": "estamos jugando" },
            // Difficulty 4 (4 questions) - Futuro Simple (ir + a + infinitivo)
            { "id": "es-grammar-4-1", "difficulty": 4, "type": "mcq" as const, "question": "Mañana ____ (llover).", "options": ["lluevo", "llueves", "lloverá", "va a llover"], "answer": "va a llover" },
            { "id": "es-grammar-4-2", "difficulty": 4, "type": "mcq" as const, "question": "Ellos ____ (viajar) a Europa el próximo año.", "options": ["viajo", "viajas", "viajarán", "van a viajar"], "answer": "van a viajar" },
            { "id": "es-grammar-4-3", "difficulty": 4, "type": "mcq" as const, "question": "Ella ____ (estar) feliz de verte.", "options": ["estoy", "estás", "estará", "va a estar"], "answer": "va a estar" },
            { "id": "es-grammar-4-4", "difficulty": 4, "type": "mcq" as const, "question": "Nosotros ____ (tener) una reunión la próxima semana.", "options": ["tengo", "tienes", "tendremos", "vamos a tener"], "answer": "vamos a tener" },
            // Difficulty 5 (4 questions) - Pretérito Perfecto Compuesto
            { "id": "es-grammar-5-1", "difficulty": 5, "type": "mcq" as const, "question": "Yo ya ____ (ver) esa película.", "options": ["veo", "ves", "vi", "he visto"], "answer": "he visto" },
            { "id": "es-grammar-5-2", "difficulty": 5, "type": "mcq" as const, "question": "¿Tú alguna vez ____ (estar) en París?", "options": ["he estado", "has estado", "ha estado", "hemos estado"], "answer": "has estado" },
            { "id": "es-grammar-5-3", "difficulty": 5, "type": "mcq" as const, "question": "Ella ya ____ (terminar) su trabajo.", "options": ["termino", "terminas", "terminó", "ha terminado"], "answer": "ha terminado" },
            { "id": "es-grammar-5-4", "difficulty": 5, "type": "mcq" as const, "question": "Ellos ____ (vivir) aquí por cinco años.", "options": ["vivo", "vives", "viven", "han vivido"], "answer": "han vivido" },
            // Difficulty 6 (4 questions) - Condicionales - Primer Condicional
            { "id": "es-grammar-6-1", "difficulty": 6, "type": "mcq" as const, "question": "Si ____ (llover), nos quedaremos en casa.", "options": ["lluevo", "llueves", "llueve", "lloverá"], "answer": "llueve" },
            { "id": "es-grammar-6-2", "difficulty": 6, "type": "mcq" as const, "question": "Si estudias mucho, ____ (aprobar) el examen.", "options": ["aprobaré", "aprobarás", "aprobará", "aprobarás"], "answer": "aprobarás" },
            { "id": "es-grammar-6-3", "difficulty": 6, "type": "mcq" as const, "question": "Ella se enojará si él ____ (llegar) tarde.", "options": ["llego", "llegas", "llega", "llegará"], "answer": "llega" },
            { "id": "es-grammar-6-4", "difficulty": 6, "type": "mcq" as const, "question": "Si ellos no se ____ (apresurar), perderán el autobús.", "options": ["apuro", "apuras", "apura", "apuran"], "answer": "apuran" }
        ]
    }
}

export { database }